### ISSUE TITLE
Nondeterminstic failure when looking for random files that are not links

### ISSUE THREAD

**Issue by phistakis** [thombashi/NFStest#1]
get_file_obj chooses a random file from self.n_files, but sometimes we want the file to fulfill a specific criteria (e.g. to be a soft link), and then it was repeatedly called until criteria is fulfilled with a max retry count of 10.
sometimes, all 10 retries produce such "bad" files, and then the test fails
when working randomly, such improbable cases will eventually happen.

**Comment by thombashi** [comment]
Great.
Thank you for your pull request.
